import type { AccountRole } from "@/lib/auth/roles";

export interface Profile {
  id: string;
  user_id: string;
  full_name: string;
  email: string;
  avatar_url?: string;
  /**
   * Legacy free-form role column from migration 001. Never read
   * by the app since 017_account_sharing.sql introduced the typed
   * `account_role` enum. Flagged for removal in a later cleanup
   * migration — kept on the type so existing destructures don't
   * break.
   */
  role: string;
  /**
   * Opted-in beta feature keys for this account. The column survives
   * for future beta gates; no current feature reads it (Flows was
   * the last user and went to soft-GA in PR #134). Defaults to `[]`
   * for every profile; toggled per-account via a direct UPDATE on
   * the `profiles` row.
   */
  beta_features?: string[];
  /**
   * Account this profile is a member of. Added by
   * `017_account_sharing.sql`; NOT NULL in the DB post-backfill.
   * Optional on the type only because older serialised payloads
   * (cached client state, test fixtures) may not have it yet.
   */
  account_id?: string;
  /**
   * Caller's role within their account. Source of truth for every
   * role-gated UI / API check — call `hasMinRole` from
   * `@/lib/auth/roles` rather than comparing this string directly.
   */
  account_role?: AccountRole;
  created_at: string;
}

// ============================================================
// Account-sharing entities (017_account_sharing.sql)
// ============================================================

export interface Account {
  id: string;
  name: string;
  /** auth.users.id of the immutable owner. */
  owner_user_id: string;
  created_at: string;
  updated_at: string;
}

/**
 * Hydrated member row for the Settings → Members tab. Combines
 * the profile and its account_role for a single member of the
 * caller's account. Sensitive fields (email) are populated only
 * when the caller has admin+ — agents and viewers see name +
 * avatar + role only.
 */
export interface AccountMember {
  user_id: string;
  full_name: string;
  email: string | null;
  avatar_url: string | null;
  role: AccountRole;
  joined_at: string;
}

/**
 * Outstanding invite link row. `token_hash` is intentionally
 * absent — it lives only in the DB and on the server. The
 * plaintext token is returned once at creation time and surfaced
 * via the invite URL; never re-emitted.
 */
export interface AccountInvitation {
  id: string;
  account_id: string;
  /** Roles offered via invite — owner is never offered. */
  role: Exclude<AccountRole, "owner">;
  created_by_user_id: string | null;
  label: string | null;
  created_at: string;
  expires_at: string;
  accepted_at: string | null;
  accepted_by_user_id: string | null;
}

export interface Contact {
  id: string;
  user_id: string;
  account_id: string;
  /** Nullable since migration 044 — an Instagram- or Messenger-only
   *  contact (DMs but never shares a phone number) has no phone. A
   *  contact always has at least one of
   *  `phone`/`instagram_id`/`messenger_id` (DB CHECK, widened by
   *  migration 066). */
  phone?: string | null;
  /** Digits-only form of `phone`, generated by the DB (migration 022)
   *  and unique per account. Read-only. */
  phone_normalized?: string;
  /** Instagram-scoped id (IGSID) of the customer, set when this
   *  contact was created from an Instagram DM (migration 044).
   *  Unique per account. */
  instagram_id?: string | null;
  /** Page-Scoped ID (PSID) of the customer, set when this contact was
   *  created from a Facebook Messenger DM (migration 066). Unique per
   *  account. */
  messenger_id?: string | null;
  name?: string;
  email?: string;
  company?: string;
  /** Date of birth (migration 044). ISO 'YYYY-MM-DD' or null. */
  date_of_birth?: string | null;
  /** Marital status + spouse (migration 045). `spouse_name` is only
   *  populated when `marital_status` is 'Married'. */
  marital_status?: string | null;
  spouse_name?: string | null;
  avatar_url?: string;
  /** Structured postal address (migration 033). All nullable. */
  street?: string;
  locality?: string;
  city?: string;
  state?: string;
  pin_code?: string;
  /** Flagged as spam from the inbox contact panel (migration 030). */
  is_spam?: boolean;
  /** Notifications suppressed for this contact (migration 034). */
  is_muted?: boolean;
  /** Contact blocked (migration 034). */
  is_blocked?: boolean;
  /** Marketing consent (migration 043). FALSE/absent = opted in
   *  ("marketing enabled"); TRUE = opted out. Drives Segment marketing
   *  rules and campaign exclusion. */
  marketing_opt_out?: boolean;
  created_at: string;
  updated_at: string;
}

/** Kind of media a WhatsApp template header can carry. */
export type MediaKind = 'image' | 'video' | 'document';

/** A reusable file in the media library (migration 036). */
export interface MediaLibraryItem {
  id: string;
  account_id: string;
  user_id: string;
  name: string;
  kind: MediaKind;
  mime_type: string;
  size_bytes: number;
  width?: number | null;
  height?: number | null;
  bucket: string;
  path: string;
  public_url: string;
  created_at: string;
}

export interface Tag {
  id: string;
  user_id: string;
  name: string;
  color: string;
  created_at: string;
}

export interface ContactTag {
  id: string;
  contact_id: string;
  tag_id: string;
}

export interface CustomField {
  id: string;
  user_id: string;
  /** Tenancy key — NOT NULL since migration 017. */
  account_id: string;
  field_name: string;
  field_type: string;
  field_options?: Record<string, unknown>;
  created_at: string;
}

export interface ContactCustomValue {
  id: string;
  contact_id: string;
  custom_field_id: string;
  value?: string;
}

export interface ContactNote {
  id: string;
  contact_id: string;
  user_id: string;
  note_text: string;
  created_at: string;
}

export type ListStatus = 'active' | 'archived';

/**
 * A named, manually-managed collection of contacts for campaign
 * targeting (migration 042). Contact<->list is many-to-many via
 * `ContactList`; a list stores only references — no filter logic
 * (that's the separate, not-yet-built Segments module).
 */
export interface List {
  id: string;
  account_id: string;
  name: string;
  description?: string | null;
  color?: string | null;
  status: ListStatus;
  /** Denormalized count of contact_lists rows, kept in sync by a DB
   *  trigger (migration 042) — avoids an N+1 count query per row on
   *  the list-of-lists page. */
  total_contacts: number;
  /** auth.users.id of whoever created the list. Null if that user was
   *  later removed (ON DELETE SET NULL). */
  created_by: string | null;
  created_at: string;
  updated_at: string;
}

/**
 * One contact's membership in one list (migration 042). Deleting a
 * row removes the contact from the list only — the contact record
 * itself is untouched. `(contact_id, list_id)` is unique.
 */
export interface ContactList {
  id: string;
  contact_id: string;
  list_id: string;
  added_at: string;
  added_by: string | null;
  contact?: Contact;
}

// ── Segments (dynamic, rule-based audiences — migration 043) ──────────
// A Segment stores ONLY filter rules; matching contacts are evaluated on
// demand server-side, so membership is always current. Contrast with
// List, which stores explicit membership.

export type SegmentCombinator = 'and' | 'or';

/** One leaf condition, e.g. { field: 'city', op: 'equals', value: 'Kolkata' }.
 *  `field` is a catalog key (see lib/segments/fields) or 'custom:<uuid>'. */
export interface SegmentRule {
  field: string;
  op: string;
  value?: string;
}

/** A nested group of rules/subgroups joined by AND or OR. */
export interface SegmentGroup {
  combinator: SegmentCombinator;
  rules: SegmentNode[];
}

export type SegmentNode = SegmentGroup | SegmentRule;

/** Narrowing helper — a node is a group iff it carries `rules`. */
export function isSegmentGroup(node: SegmentNode): node is SegmentGroup {
  return (node as SegmentGroup).rules !== undefined;
}

export type SegmentStatus = 'active' | 'archived';

export interface Segment {
  id: string;
  account_id: string;
  name: string;
  description?: string | null;
  color?: string | null;
  status: SegmentStatus;
  /** Root rule group. Evaluated by the `segment_count` /
   *  `segment_contacts_page` RPCs — never stores contacts. */
  rules: SegmentGroup;
  /** Cached estimate for the list page; NULL until first computed. */
  estimated_count: number | null;
  count_computed_at: string | null;
  created_by: string | null;
  created_at: string;
  updated_at: string;
}

export type ConversationStatus = 'open' | 'pending' | 'closed';

export type ConversationChannel = 'whatsapp' | 'instagram' | 'messenger';

export interface Conversation {
  id: string;
  user_id: string;
  contact_id: string;
  status: ConversationStatus;
  /** Which messaging channel this conversation belongs to (migration
   *  044). Defaults to 'whatsapp' for every pre-existing row. */
  channel: ConversationChannel;
  assigned_agent_id?: string;
  /** Flow (bot) currently driving this conversation, if any (migration
   *  035). Mutually exclusive with `assigned_agent_id` in the UI. */
  assigned_flow_id?: string | null;
  /** The account's AI agent owns this thread (migration 041): it
   *  auto-replies to every inbound here regardless of the account-wide
   *  toggle and without the per-conversation cap. Mutually exclusive
   *  with `assigned_agent_id` / `assigned_flow_id`. */
  ai_agent_assigned?: boolean;
  last_message_text?: string;
  last_message_at?: string;
  /** Timestamp of the last inbound customer message — used to compute the WhatsApp 24-hour messaging window. */
  customer_replied_at?: string;
  unread_count: number;
  created_at: string;
  updated_at: string;
  contact?: Contact;
}

export type SenderType = 'customer' | 'agent' | 'bot';
export type ContentType =
  | 'text'
  | 'image'
  | 'document'
  | 'audio'
  | 'video'
  | 'location'
  | 'template'
  /** Customer tapped a reply button or list row on a message we sent. */
  | 'interactive'
  /** A WhatsApp voice-call event (inbound), surfaced inline in the thread
   *  as a call chip. The structured record lives in `call_logs`. */
  | 'call'
  /** Customer completed a WhatsApp Form (migration 069) — the answers
   *  live in `form_answers`, keyed by field label where the
   *  originating form could be resolved, by raw field id otherwise. */
  | 'form_response';
export type MessageStatus = 'sending' | 'sent' | 'delivered' | 'read' | 'failed';

export interface Message {
  id: string;
  conversation_id: string;
  sender_type: SenderType;
  sender_id?: string;
  content_type: ContentType;
  content_text?: string;
  media_url?: string;
  template_name?: string;
  message_id?: string;
  status: MessageStatus;
  created_at: string;
  reply_to_message_id?: string;
  /**
   * Only set when `content_type === 'interactive'` — the stable id of
   * the button or list row the customer tapped. The Flows engine uses
   * this to route the next node; the inbox bubble uses it as a styling
   * cue (renders with a "↩ button reply" affordance).
   */
  interactive_reply_id?: string;
  /** Set on an outbound message that sent a Form, and on the inbound
   *  `form_response` that answers it (migration 069). */
  whatsapp_form_id?: string | null;
  /** Only on a `form_response` row — the customer's answers, keyed by
   *  field label when resolvable, by raw field id otherwise. */
  form_answers?: Record<string, unknown> | null;
}

export type CallDirection = 'inbound' | 'outbound';
/** Free-text in the DB (Meta's terminate statuses for this new API aren't
 *  finalized); these are the values the webhook currently maps to. */
export type CallStatus =
  | 'ringing'
  | 'completed'
  | 'missed'
  | 'declined'
  | 'failed';

export interface CallLog {
  id: string;
  account_id: string;
  conversation_id?: string | null;
  contact_id?: string | null;
  /** Meta's call id. */
  wa_call_id: string;
  direction: CallDirection;
  status: CallStatus | string;
  started_at?: string | null;
  ended_at?: string | null;
  duration_seconds?: number | null;
  created_at: string;
  updated_at: string;
}

export type ReactionActor = 'customer' | 'agent';

export interface MessageReaction {
  id: string;
  message_id: string;
  conversation_id: string;
  actor_type: ReactionActor;
  actor_id?: string;
  emoji: string;
  created_at: string;
}

export interface WhatsAppConfig {
  id: string;
  user_id: string;
  phone_number_id: string;
  waba_id?: string;
  access_token: string;
  verify_token?: string;
  status: 'connected' | 'disconnected';
  connected_at?: string;
  /**
   * Set when POST /{phone_number_id}/register last succeeded. NULL
   * means the number was saved but never actually subscribed for
   * webhooks on Meta's side — inbound events will be silently lost.
   */
  registered_at?: string;
  /** Set when POST /{waba_id}/subscribed_apps last succeeded. */
  subscribed_apps_at?: string;
  /** Last error from /register; cleared on success. */
  last_registration_error?: string;
  /**
   * Encrypted 2-step PIN set during Embedded Signup registration.
   * Meta requires the same PIN for any later re-registration, so we
   * persist it (AES-256-GCM, same scheme as access_token). NULL for
   * manual-credential rows where the user supplies the PIN by hand.
   */
  registration_pin?: string;
}

/**
 * Instagram DM connection for an account (migration 044). One row per
 * account, manual-credential connect flow (no OAuth/Embedded-Signup
 * yet) — the user pastes a Page Access Token + IDs generated in Meta's
 * dashboard. Mirrors `WhatsAppConfig` but simplified: no /register+PIN
 * dance or WABA-subscribe step, since those are WhatsApp Cloud
 * API-specific with no Instagram equivalent.
 */
/** Which flow produced an `InstagramConfig` row (migration 046). The
 *  two mint tokens from different Meta API hosts — graph.instagram.com
 *  for 'oauth' vs graph.facebook.com for the legacy 'manual' Page-token
 *  path — so this matters for troubleshooting. */
export type InstagramConnectMethod = 'manual' | 'oauth';

export interface InstagramConfig {
  id: string;
  account_id: string;
  created_by?: string | null;
  /** Facebook Page id linked to the Instagram Professional account.
   *  Null for 'oauth' rows — Instagram Business Login (migration 046)
   *  connects directly, with no linked Page at all. */
  page_id?: string | null;
  /** The IG business account node id — used as the sender identity
   *  for outbound sends and to resolve inbound webhook events. */
  instagram_business_account_id: string;
  access_token: string;
  verify_token?: string | null;
  status: 'connected' | 'disconnected';
  connect_method: InstagramConnectMethod;
  connected_at?: string | null;
  /** Set when POST /{page_id}/subscribed_apps last succeeded
   *  (best-effort, non-fatal on failure). Only applies to 'manual' rows. */
  subscribed_at?: string | null;
  last_verification_error?: string | null;
  created_at: string;
  updated_at: string;
}

// Raw Meta status enum. We persist this verbatim from Meta (sync + webhook)
// rather than collapsing to a local TitleCase set — distinctions like
// PAUSED vs DISABLED vs IN_APPEAL drive the edit/resubmit/delete flows.
// DRAFT is the local-only state before the row is submitted to Meta.
export type MessageTemplateStatus =
  | 'DRAFT'
  | 'PENDING'
  | 'APPROVED'
  | 'REJECTED'
  | 'PAUSED'
  | 'DISABLED'
  | 'IN_APPEAL'
  | 'PENDING_DELETION';

export type TemplateButton =
  | { type: 'QUICK_REPLY'; text: string }
  | { type: 'URL'; text: string; url: string; example?: string }
  | { type: 'PHONE_NUMBER'; text: string; phone_number: string }
  | { type: 'COPY_CODE'; text: string; example: string };

export interface TemplateSampleValues {
  body?: string[];
  header?: string[];
  /** Authentication-template config. Stored in this JSONB column so no
   *  schema migration is needed — Marketing/Utility rows simply omit it. */
  auth?: {
    add_security_recommendation?: boolean;
    code_expiration_minutes?: number;
  };
}

/** One card of a carousel template. All cards in a template share the
 *  same media format and the same button structure (Meta rule); only
 *  the media, body, and per-button values differ per card. */
export interface CarouselCard {
  /** Public URL of the card's media (image or video). */
  media_url: string;
  /** Resumable-Upload handle, derived at submit time. */
  media_handle?: string;
  body_text: string;
  buttons: TemplateButton[];
}

export type TemplateType = 'standard' | 'carousel';

export interface MessageTemplate {
  id: string;
  user_id: string;
  name: string;
  category: 'Marketing' | 'Utility' | 'Authentication';
  language?: string;
  /** 'standard' (default) or 'carousel'. */
  template_type?: TemplateType;
  header_type?: 'text' | 'image' | 'video' | 'document';
  header_content?: string;
  header_handle?: string;
  header_media_url?: string;
  body_text: string;
  footer_text?: string;
  buttons?: TemplateButton[];
  /** Carousel-only: shared media format + the cards. */
  carousel_card_format?: 'image' | 'video';
  carousel_cards?: CarouselCard[];
  sample_values?: TemplateSampleValues;
  status?: MessageTemplateStatus;
  meta_template_id?: string;
  rejection_reason?: string;
  quality_score?: 'GREEN' | 'YELLOW' | 'RED';
  submission_error?: string;
  last_submitted_at?: string;
  created_at: string;
}

/** Native WhatsApp Flow, authored as a "Form" — see
 *  src/lib/whatsapp/forms.ts for why the product name differs from
 *  Meta's (it would collide with the unrelated Flows bot builder). */
export type FormFieldType =
  | 'short_text'
  | 'email'
  | 'phone'
  | 'number'
  | 'long_text'
  | 'dropdown'
  | 'radio'
  | 'checkbox'
  | 'date'
  | 'opt_in';

export interface FormFieldOption {
  id: string;
  title: string;
}

export interface FormField {
  id: string;
  type: FormFieldType;
  label: string;
  required: boolean;
  options?: FormFieldOption[];
}

/** Mirrors Meta's own Flow status values verbatim. */
export type WhatsAppFormStatus = 'DRAFT' | 'PUBLISHED' | 'DEPRECATED' | 'BLOCKED' | 'THROTTLED';

export interface WhatsAppForm {
  id: string;
  account_id: string;
  created_by?: string | null;
  name: string;
  categories: string[];
  fields: FormField[];
  meta_flow_id?: string | null;
  status: WhatsAppFormStatus;
  validation_errors: unknown[];
  created_at: string;
  updated_at: string;
}

export interface Pipeline {
  id: string;
  user_id: string;
  name: string;
  created_at: string;
}

export interface PipelineStage {
  id: string;
  pipeline_id: string;
  name: string;
  position: number;
  color: string;
  created_at: string;
}

export type DealStatus = 'open' | 'won' | 'lost';

export interface Deal {
  id: string;
  user_id: string;
  pipeline_id: string;
  stage_id: string;
  /**
   * Nullable after migration 004 — becomes NULL when the referenced
   * contact is deleted (ON DELETE SET NULL). History preserved.
   */
  contact_id: string | null;
  conversation_id?: string;
  assigned_to?: string;
  title: string;
  value: number;
  currency?: string;
  notes?: string;
  expected_close_date?: string;
  status?: DealStatus;
  created_at: string;
  updated_at?: string;
  contact?: Contact;
  stage?: PipelineStage;
  assignee?: Profile;
}

export type BroadcastStatus = 'draft' | 'scheduled' | 'sending' | 'sent' | 'failed';
export type RecipientStatus = 'pending' | 'sent' | 'delivered' | 'read' | 'replied' | 'failed';

export interface Broadcast {
  id: string;
  user_id: string;
  name: string;
  template_name: string;
  template_language: string;
  template_variables?: Record<string, unknown>;
  audience_filter?: Record<string, unknown>;
  scheduled_at?: string;
  status: BroadcastStatus;
  total_recipients: number;
  sent_count: number;
  delivered_count: number;
  read_count: number;
  replied_count: number;
  failed_count: number;
  created_at: string;
}

export interface BroadcastRecipient {
  id: string;
  broadcast_id: string;
  /**
   * Nullable after migration 004 — becomes NULL when the referenced
   * contact is deleted (ON DELETE SET NULL). History preserved; the
   * UI renders "Unknown" for orphaned rows.
   */
  contact_id: string | null;
  status: RecipientStatus;
  sent_at?: string;
  delivered_at?: string;
  read_at?: string;
  replied_at?: string;
  error_message?: string;
  /**
   * Meta's message id, persisted when the broadcast send succeeds so
   * the webhook can mirror status updates back onto the recipient row.
   * Added in migration 003.
   */
  whatsapp_message_id?: string;
  created_at: string;
  contact?: Contact;
}

// ============================================================
// Quick replies (migration 052)
// ============================================================

/**
 * A canned agent reply, expanded in the composer by typing `/shortcut`.
 * Account-scoped and shared across the team. Unrelated to Meta's template
 * QUICK_REPLY *button* type — these are plain text, never sent to Meta as
 * a template.
 */
export interface QuickReply {
  id: string;
  account_id: string;
  /** Creator (audit only); null once that user is deleted. */
  user_id: string | null;
  /** Token typed after '/'. Matches ^[A-Za-z0-9_-]{1,32}$, unique per account. */
  shortcut: string;
  body: string;
  created_at: string;
  updated_at: string;
}

// ============================================================
// Support tickets (migration 053)
// ============================================================

export type SupportTicketCategory =
  | 'general'
  | 'billing'
  | 'technical'
  | 'feature'
  | 'other';

export type SupportTicketPriority = 'low' | 'normal' | 'high';

export type SupportTicketStatus = 'open' | 'pending' | 'resolved' | 'closed';

/** Who wrote a ticket message — the customer, or the product support team. */
export type SupportMessageAuthorRole = 'user' | 'support';

/**
 * An in-app support ticket. Account-scoped and shared across the team.
 * The unread signal compares `last_support_reply_at` against
 * `user_last_read_at` (both maintained by migration 053).
 */
export interface SupportTicket {
  id: string;
  account_id: string;
  /** Creator (audit only); null once that user is deleted. */
  user_id: string | null;
  subject: string;
  category: SupportTicketCategory;
  priority: SupportTicketPriority;
  status: SupportTicketStatus;
  last_message_at: string | null;
  last_support_reply_at: string | null;
  user_last_read_at: string | null;
  created_at: string;
  updated_at: string;
}

/** One message in a support ticket thread. */
export interface SupportTicketMessage {
  id: string;
  ticket_id: string;
  account_id: string;
  author_role: SupportMessageAuthorRole;
  /** Author (audit only); null for support messages / deleted users. */
  user_id: string | null;
  body: string;
  created_at: string;
}

// ============================================================
// Automations (migration 006)
// ============================================================

export type AutomationTriggerType =
  | 'new_message_received'
  | 'first_inbound_message'
  | 'keyword_match'
  | 'new_contact_created'
  | 'conversation_assigned'
  | 'tag_added'
  | 'time_based';

export type AutomationStepType =
  | 'send_message'
  | 'send_template'
  | 'send_buttons'
  | 'add_tag'
  | 'remove_tag'
  | 'assign_conversation'
  | 'update_contact_field'
  | 'create_deal'
  | 'wait'
  | 'condition'
  | 'send_webhook'
  | 'close_conversation';

export type AutomationLogStatus = 'success' | 'partial' | 'failed';

export interface KeywordMatchTriggerConfig {
  keywords: string[];
  match_type: 'exact' | 'contains';
  case_sensitive?: boolean;
}

export interface TagTriggerConfig {
  tag_id: string;
}

export interface TimeBasedTriggerConfig {
  /** Cron expression or simple HH:mm string; engine can accept either. */
  schedule: string;
  timezone?: string;
}

export type AutomationTriggerConfig =
  | Record<string, never>
  | KeywordMatchTriggerConfig
  | TagTriggerConfig
  | TimeBasedTriggerConfig
  | Record<string, unknown>;

export interface SendMessageStepConfig {
  text: string;
}

export interface SendTemplateStepConfig {
  template_name: string;
  language?: string;
  variables?: Record<string, string>;
}

export interface SendButtonsStepConfig {
  /** Body text; can interpolate {{ vars.* }} / {{ message.text }}. */
  text: string;
  /** Optional plain-text header (≤ 60 chars per Meta). */
  header_text?: string;
  /** Optional grey footer line under the buttons (≤ 60 chars per Meta). */
  footer_text?: string;
  /** 1-3 buttons; Meta's interactive-button cap. */
  buttons: Array<{
    /** Stable id sent back by Meta when this button is tapped. */
    id: string;
    /** Visible label (≤ 20 chars per Meta). */
    title: string;
  }>;
}

export interface TagStepConfig {
  tag_id: string;
}

export interface AssignConversationStepConfig {
  mode: 'specific' | 'round_robin';
  agent_id?: string;
}

export interface UpdateContactFieldStepConfig {
  /**
   * Either a built-in contact column (`name` | `email` | `company`) or a
   * custom field encoded as `custom:<custom_field_id>`. The `custom:` prefix
   * is how the engine distinguishes a `contact_custom_values` write from a
   * direct `contacts` column update. Older configs store the bare column name,
   * so this stays backward compatible.
   */
  field: string;
  /** Supports `{{ vars.* }}` / `{{ message.text }}` interpolation at runtime. */
  value: string;
}

export interface CreateDealStepConfig {
  pipeline_id: string;
  stage_id: string;
  title: string;
  value?: number;
}

export interface WaitStepConfig {
  amount: number;
  unit: 'minutes' | 'hours' | 'days';
}

export type ConditionSubject =
  | 'contact_field'
  | 'tag_presence'
  | 'message_content'
  | 'time_of_day';

export interface ConditionStepConfig {
  subject: ConditionSubject;
  /** e.g. field name, tag id, substring, or "HH:mm-HH:mm" depending on subject */
  operand?: string;
  /** For contact_field equals / message_content contains — comparison value */
  value?: string;
}

export interface SendWebhookStepConfig {
  url: string;
  headers?: Record<string, string>;
  body_template?: string;
}

export type AutomationStepConfig =
  | SendMessageStepConfig
  | SendTemplateStepConfig
  | SendButtonsStepConfig
  | TagStepConfig
  | AssignConversationStepConfig
  | UpdateContactFieldStepConfig
  | CreateDealStepConfig
  | WaitStepConfig
  | ConditionStepConfig
  | SendWebhookStepConfig
  | Record<string, never>
  | Record<string, unknown>;

export interface Automation {
  id: string;
  /** Account tenancy key — every automation belongs to one account
   *  (migration 017 made the column NOT NULL). The engine looks up
   *  active automations by this field on inbound webhook events. */
  account_id: string;
  /** Original author. Used for log audit + outbound message
   *  sender-of-record, never for tenancy isolation. */
  user_id: string;
  name: string;
  description?: string;
  trigger_type: AutomationTriggerType;
  trigger_config: AutomationTriggerConfig;
  is_active: boolean;
  execution_count: number;
  last_executed_at?: string | null;
  created_at: string;
  updated_at: string;
}

export interface AutomationStep {
  id: string;
  automation_id: string;
  parent_step_id?: string | null;
  branch?: 'yes' | 'no' | null;
  step_type: AutomationStepType;
  step_config: AutomationStepConfig;
  position: number;
  created_at: string;
}

export interface AutomationLogStepResult {
  step_id: string;
  step_type: AutomationStepType;
  status: 'success' | 'skipped' | 'failed';
  detail?: string;
}

export interface AutomationLog {
  id: string;
  automation_id: string;
  user_id: string;
  contact_id: string | null;
  trigger_event: string;
  steps_executed: AutomationLogStepResult[];
  status: AutomationLogStatus;
  error_message?: string | null;
  created_at: string;
  contact?: Contact;
}
